const ONBOARDING_NAVIGATION_POP = 'ONBOARDING_NAVIGATION_POP';
const ONBOARDING_NAVIGATION_PUSH = 'ONBOARDING_NAVIGATION_PUSH';

const ONBOARDING_ROUTE_HELLO = 'ONBOARDING_ROUTE_HELLO';
const ONBOARDING_ROUTE_PROFILE_PICTURE = 'ONBOARDING_ROUTE_PROFILE_PICTURE';
const ONBOARDING_ROUTE_CAMERA_ROLL = 'ONBOARDING_ROUTE_CAMERA_ROLL';

export {
  ONBOARDING_NAVIGATION_POP,
  ONBOARDING_NAVIGATION_PUSH,

  ONBOARDING_ROUTE_HELLO,
  ONBOARDING_ROUTE_PROFILE_PICTURE,
  ONBOARDING_ROUTE_CAMERA_ROLL,
};
