language: android
android:
  components:
    - build-tools-23.0.1
    - android-23

    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16

script: ./android/gradlew build assembleRelease



# node_js:
#   - "6"
#
# script:
#   -npm run ci
#
# # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
