language: android
env:
  global:
    secure: b9QYFLrBMuEtRt1WMretxwYUofA1qPoFCa6Ckd2I+Fxgbr/ozQKzYS76iGicYzV5pOblQVo1Kx3HpUcxY5R/+Str68ejLgAVinQ+RQPwC+8KFKBf9UI8WUMPMEECx+WcVFRzZz9sUivRyqP5cIzxoP9GsqpaXDsWjueHnveqsd1q2yeLrZSEizDWfRsnYlkRKapIRN55Tyq2V3MB1nilYc9Z3DcdiiLt4UkPOiNsjHKhdKgHkkjKviMbAUwMuFfBSt055ABS8BNAvbit4Jp7QhZsRVszP+byboOv1FYK6pFc7et0KgP8bUBbV1nQP6LAPRoWpTmtceM4Q+efYKp/Rw5pxPv9yx/Uc6oztJihKTSt7gPr8eDJeyU2pnUZMobqJJMBW1gfeCGHdRZc6SrHU8poTTSh61KMfhfUZO60th0HRClkR57CWBnXyevzXtH5dTqVItSukMOjJPe0SleriEtmMEvqM8FA+4wSCO92M1rCWx/CgTtYh4HqS7YVuMzC0c6gnhTYdhwcP1xhhb2ou6Q11iJBmImOJZ14e34KJ6KQpMbtwvLyFmuZZzpcNrzTaFwxZZcIX6LOAj3f0yq1QT2DufXb93ADahsosyFazZtYnBjgufLNoUW3+HFCYb9DcujP2KlRq95DMGDdjfrWwyu+bxtdOfrhKSajrY03fSs=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - node_modules
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- openssl aes-256-cbc -K $encrypted_0d629920e50c_key -iv $encrypted_0d629920e50c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- '[ -z "$TRAVIS_TAG" ] || ./utils/travis-release.sh'
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: K8QH/FSzPwOpv80XqVyn74XJ/e81qAc16KQfNl28KRqDdRVCQd4IXA8K0JwMbw7H2Tn72U3MgUdErVsjV4ORziBUhsbLQ9fkMTHvhNZrwQj9xnyFNHVKY5sBAUGrKEmu8qd1l8pXX2dr0yPSM+gfyxeXGeEMsQg1dDO7e+EL3nqUNHYI6kiNWqMNNHMIGpZEynLsKMnPyC3fc47D/KL0dxesaE6nrAD+CHu0wmehxvqqmk1QFjnrzyWbSTPsg4jKA83JHWfJ28F+G3qqZmAhUxYW7A9sQ97iI4RbZBjX4vr47+93Z0dJtF/Q1/AE7CqvUbo1PKX+WwUn+0r5oOaewp1hrRBwCdrQn42fLweugYxYW2Es3IAsD1cgF/hjX6nr+NzuTwaNvTyTrPgAYAM4C6aspCgGBzQ8f9LxFDoPvVKVOoIgt2pT1LLb0biJd8ooesuB4N2S8U/goVu7jcHYeLkUfmibopf03brmtmclLAZMCrlyQKIbR1dMhQ0TE57w1JNyTE26mqAa3ZXRBD6dkcPvB1MZaW3LFX+mPvv8aC6Ew5n660dlYnjvKykKjJtoRmubc1OMxLuOk3HiiA3Vf/XvrZTKQ3UXK9rluE3TRcRZc+VUNa4nNNY2NiV8wnsQsPIlDj6Wdn1GCNESRfjO8AC3ElHa0jIZnJ0kspw/SD8=
  file:
  - $TRAVIS_BUILD_DIR/$TRAVIS_TAG.apk
  - $TRAVIS_BUILD_DIR/$TRAVIS_TAG.qa.apk
  on:
    repo: praekeltfoundation/mentorship-droid
    tags: true
