language: android
env:
- secure: teBBGzYfdXY+NCuWP+EqY8McBgDUHPKnZmlH/cLTr2doduxHJqCe5NSBBOnlgSCSExLX1K5gj0si0BixpAyE/BKATLnlzhFgP9d3emE2dSLLZtjCe0bt6+JMsnjqUMSo5zW2FepoLVE4UgQ1A9curOu0DooR8y2AJKhsdYluDFV9nfC6a4JgYlRkg+zHl/88vuzy63TawBH14mql5EdJ6FmJJvEqhaoULWUzS+RdYjCv3h/Kwp0ujg5hntnXFi3/JfAv+mkF3zrnh4QrtoFy4ZVshqhrBLRZKXoz3MAGzx/2w8yu6m0n77PBvhQRjZX6lo0fev6fOkWBCY3KiUpZjRmx8Sq4QXSD6Y/vRwQi+VfmCzBIulLGS0HeQkeXPjFBMDSUiOcDRzXRqQbE93MDF5ZfkYTbjIzgvSpeSUKmZj2bAarrODkmgVc31/x70rqK2vKfQ3XCZqXvK+kgdGGYh+WfJvfLQs29tNBr0D9JzlHw7Vva1472WSFK9POFfo9J1MQoOizAYi0z3mCgYicLgtE1cJlS3h0gmk4O/9dikK7l98tA3bm4JeG/UWrIaUirQNRUY9TVIbbZfKh6yc/PdCbJ2gGipnHJDAliiHqTaLOIQzDN/UILH4+/y68wd9YSwyX2+AtgEk4UpCLmLPOUlxSCaK3/EPeIyhGGUWbQcFE=
before_install:
- openssl aes-256-cbc -K $encrypted_34dbe72c01ad_key -iv $encrypted_34dbe72c01ad_iv
  -in android/app/google-services.json.enc -out android/app/google-services.json -d
- openssl aes-256-cbc -K $encrypted_34dbe72c01ad_key -iv $encrypted_34dbe72c01ad_iv
  -in android/app/release.keystore.enc -out android/app/release.keystore -d
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- cd android && ./gradlew assembleRelease -PdisablePreDex
deploy:
  provider: releases
  api_key:
    secure: Fyk/c5dWqX/qzjXRnnJLItYLAfICjY2kvZ1bIHcD7QmGy46w/8779aWcS7j/LhfNZzair6fg1rOz+2c1nnjIOuBNOnxBncduo+IsNX1uh+xSB9ljGDLsAudwLGQZvg0GWJzseFwSSZlyDjPCQvFGXldPNnmQVAwZwRdrd1Q181vTYnOyPx/ujp6m/xHeTMZNUSXjbnSUhLe3GLMQ/kHKDcYH5TR42Nn2R9F0Elz2T+tqGzaMs08jeDoEYvCwaW7gjowCz0U+S+0qyoGmtkiiNYie9nGT6lkT6mI90UcHeWKdYqPMjpXY0WXznOa5qtvXf+gV1r2jWhlP49hnD3RhdkNx2mzMEo3A0d1qwiIjgCVhuaxdwH0mHcB3pHIdTal2MOGQYxKM4DDMggMKdHXBA9d8HlKMx8nFmtoXe8xZYH0E+OeXOPXZ0bt+5VuWXZyIHCwtGMi+kZrEe/ckIDGDFIOlDPQhyVdrup186lIJ02TjSs66yA7Fz3I9sJ5cl/e5rpNFuCUlqKGzCU/BXWTDzYbSuAloKuL9l2QAFsJrl8fGHb91Fhvfb9k7E/xIOGbpt5XtuLq0A0JH5zICWMNvQvXy+Hqr/Z9VKG+QFGzWaY4cIbig7zkEBnMTW1ehJ8h1eHUB6VSvgjKCUujUV69qaA2vgtbb25vsP6aB5aoQ0xk=
  file: android/app/build/outputs/apk/app-release.apk
  on:
    repo: praekeltfoundation/mentorship-droid
    tags: true
