language: android

before_install:
  - nvm install 6
  - node --version

install:
  - npm install

env:
  - MYAPP_RELEASE_STORE_FILE=travis.keystore
  - MYAPP_RELEASE_KEY_ALIAS=my-key-alias
  - MYAPP_RELEASE_STORE_PASSWORD=123456
  - MYAPP_RELEASE_KEY_PASSWORD=123456

android:
  components:
    - build-tools-23.0.1
    - android-23

    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16

# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8

script:
  - cd android && ./gradlew assembleRelease
