language: android
env:
  global:
    secure: I7UgvD038BwQalydMSGmUMDZHXJd1yZ4/uuI++X0jA/4uu8Lp+iYoT1Fuvs7BuxJjzY+PcmP19heH//EWYkoWYbr+SbbpVLc3LZsu+x8zJFhQ/bJCfCve/f7J3S4ILwr/GSaW0t2PLKQW3dYdRkHJIvkvZU7l18wEahFn+R6t2Ka0ioHRQY0YT/y2du1nG8mOrxuk0lNmxpzBPK7o24eeSlw5tObBAtRLCepN4hMNNLOkUNSAZ5rV8m+RGFnd8P2RzU1DgndQ8cUOwtcmwYeQuL0ufNo4mBByOLUb8tXBNdGZjoaF98OR+iadiFwTIutys8Q6Stq9UnwGC/gxQYfaF3SJjMKH6/3egfZlqGad66ncQIkbROOOjN8j0xkAxqi6FCC11cMY+KgWFSbSgKlh62QjjjOzcqutq1HURQ4VUAu30UZtW+5uBnjZl7Aopn2NHQ18qdEnWiECEUoz4x3HJMeAn5cqSkC4VUKUrv3vlQS6VYpNWxMDxRGBJs1SaL/Z/vqx3RUOKhhEcY6QyqcGVs9R+7/oTM0cJD3xeWlWVrKxgoy/RO23q+Sqgrg+rBfNkGenf4df4BuiOvKNKzO8eYXPGdDwb70L6VJAtQDRPIPHn42BOiHBvDmtzurVYmoGCRwgYVlS2aVM/8yeq2i0pRbglM78CmzCBtde5ncnsk=
before_install:
- openssl aes-256-cbc -K $encrypted_c3182a2d3bfa_key -iv $encrypted_c3182a2d3bfa_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- cd android && ./gradlew assembleRelease -PdisablePreDex
deploy:
  provider: releases
  api_key:
    secure: Fyk/c5dWqX/qzjXRnnJLItYLAfICjY2kvZ1bIHcD7QmGy46w/8779aWcS7j/LhfNZzair6fg1rOz+2c1nnjIOuBNOnxBncduo+IsNX1uh+xSB9ljGDLsAudwLGQZvg0GWJzseFwSSZlyDjPCQvFGXldPNnmQVAwZwRdrd1Q181vTYnOyPx/ujp6m/xHeTMZNUSXjbnSUhLe3GLMQ/kHKDcYH5TR42Nn2R9F0Elz2T+tqGzaMs08jeDoEYvCwaW7gjowCz0U+S+0qyoGmtkiiNYie9nGT6lkT6mI90UcHeWKdYqPMjpXY0WXznOa5qtvXf+gV1r2jWhlP49hnD3RhdkNx2mzMEo3A0d1qwiIjgCVhuaxdwH0mHcB3pHIdTal2MOGQYxKM4DDMggMKdHXBA9d8HlKMx8nFmtoXe8xZYH0E+OeXOPXZ0bt+5VuWXZyIHCwtGMi+kZrEe/ckIDGDFIOlDPQhyVdrup186lIJ02TjSs66yA7Fz3I9sJ5cl/e5rpNFuCUlqKGzCU/BXWTDzYbSuAloKuL9l2QAFsJrl8fGHb91Fhvfb9k7E/xIOGbpt5XtuLq0A0JH5zICWMNvQvXy+Hqr/Z9VKG+QFGzWaY4cIbig7zkEBnMTW1ehJ8h1eHUB6VSvgjKCUujUV69qaA2vgtbb25vsP6aB5aoQ0xk=
  file: android/app/build/outputs/apk/app-release.apk
  on:
    repo: praekeltfoundation/mentorship-droid
    tags: true
