const CATEGORY_CHOOSE = 'CATEGORY_CHOOSE';
const ACTIVITY_CHOOSE = 'ACTIVITY_CHOOSE';
const ACTIVITY_SCHEDULE_CALL = 'ACTIVITY_SCHEDULE_CALL';
const ACTIVITY_CALL_NOTES_VIEW = 'ACTIVITY_CALL_NOTES_VIEW';
const ACTIVITY_SCREEN_DISMISS = 'ACTIVITY_SCREEN_DISMISS';


export {
  CATEGORY_CHOOSE,
  ACTIVITY_CHOOSE,
  ACTIVITY_SCHEDULE_CALL,
  ACTIVITY_CALL_NOTES_VIEW,
  ACTIVITY_SCREEN_DISMISS,
};
