const CATEGORY_CHOOSE = 'CATEGORY_CHOOSE';
const ACTIVITY_CHOOSE = 'ACTIVITY_CHOOSE';
const ACTIVITY_SCHEDULE_CALL = 'ACTIVITY_SCHEDULE_CALL';


export {
  CATEGORY_CHOOSE,
  ACTIVITY_CHOOSE,
  ACTIVITY_SCHEDULE_CALL,
};
