import { PROFILE_FETCH_SUCCESS } from 'src/profile/constants';

import { AUTH_LOGIN_SUCCESS } from 'src/auth/constants';

import {
  SCHEDULED_CALL_LIST_SUCCESS,
  SCHEDULED_CALL_CREATE_SUCCESS,
  SCHEDULED_CALL_FETCH_SUCCESS,
} from 'src/profile/constants';


const ACTIONS_WITH_ENTITIES = [
  AUTH_LOGIN_SUCCESS,
  PROFILE_FETCH_SUCCESS,
  SCHEDULED_CALL_LIST_SUCCESS,
  SCHEDULED_CALL_CREATE_SUCCESS,
  SCHEDULED_CALL_FETCH_SUCCESS,
];


export {
  ACTIONS_WITH_ENTITIES,
};
