const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
const AUTH_LOGIN_NOT_FOUND = 'AUTH_LOGIN_NOT_FOUND';

const AUTH_LOGOUT = 'AUTH_LOGOUT';

const AUTH_PASSWORD_RESET_REQUEST = 'AUTH_PASSWORD_RESET_REQUEST';
const AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS';
const AUTH_PASSWORD_RESET_FAILURE = 'AUTH_PASSWORD_RESET_FAILURE';

const AUTH_STATUS_IDLE = 'STATUS_IDLE';
const AUTH_STATUS_BUSY = 'STATUS_BUSY';
const AUTH_STATUS_ERROR = 'STATUS_ERROR';
const AUTH_STATUS_NOT_FOUND = 'STATUS_NOT_FOUND';


export {
  AUTH_LOGIN_REQUEST,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILURE,
  AUTH_LOGIN_NOT_FOUND,

  AUTH_LOGOUT,

  AUTH_PASSWORD_RESET_REQUEST,
  AUTH_PASSWORD_RESET_SUCCESS,
  AUTH_PASSWORD_RESET_FAILURE,

  AUTH_STATUS_IDLE,
  AUTH_STATUS_BUSY,
  AUTH_STATUS_ERROR,
  AUTH_STATUS_NOT_FOUND,
};
