export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST';
export const BLOG_POST_LIST_SUCCESS = 'BLOG_POST_LIST_SUCCESS';
export const BLOG_POST_LIST_FAILURE = 'BLOG_POST_LIST_FAILURE';

export const BLOG_POST_CHOOSE = 'BLOG_POST_CHOOSE';
