import { fromPairs } from 'lodash';
import images from 'src/constants/images';

// TODO consistent convention for namespacing of constants

export const CALL_NOTE_VERSION = '1';

export const CALL_NOTE_LIST_REQUEST = 'CALL_NOTE_LIST_REQUEST';
export const CALL_NOTE_LIST_SUCCESS = 'CALL_NOTE_LIST_SUCCESS';
export const CALL_NOTE_LIST_FAILURE = 'CALL_NOTE_LIST_FAILURE';

export const CALL_NOTE_CREATE_REQUEST = 'CALL_NOTE_CREATE_REQUEST';
export const CALL_NOTE_CREATE_SUCCESS = 'CALL_NOTE_CREATE_SUCCESS';

export const CALL_NOTE_UPDATE_REQUEST = 'CALL_NOTE_UPDATE_REQUEST';
export const CALL_NOTE_UPDATE_SUCCESS = 'CALL_NOTE_UPDATE_SUCCESS';
export const CALL_NOTE_UPDATE_FAILURE = 'CALL_NOTE_UPDATE_FAILURE';

export const CALL_NOTES_MENTEE_HAPPY = 'happy';
export const CALL_NOTES_MENTEE_SAD = 'sad';
export const CALL_NOTES_MENTEE_BORED = 'bored';
export const CALL_NOTES_MENTEE_CONFUSED = 'confused';
export const CALL_NOTES_MENTEE_UPSET = 'upset';
export const CALL_NOTES_MENTEE_WITHDRAWN = 'withdrawn';
export const CALL_NOTES_MENTEE_EXCITED = 'excited';
export const CALL_NOTES_MENTEE_ENGAGED = 'engaged';

export const CALL_NOTE_CREATE_OPEN = 'CALL_NOTE_CREATE_OPEN';
export const CALL_NOTE_RETROACTIVELY_CREATE_OPEN = 'CALL_NOTE_RETROACTIVELY_CREATE_OPEN';
export const CALL_NOTES_CHANGE_CALL_NOTE = 'CALL_NOTES_CHANGE_CALL_NOTE';
export const CALL_NOTES_VIEW_ALL = 'CALL_NOTES_VIEW_ALL';
export const CALL_NOTE_CHOOSE = 'CALL_NOTE_CHOOSE';

export const ADD_RETROACTIVELY = 'ADD_RETROACTIVELY';
export const ADD_IMMEDIATE = 'ADD_IMMEDIATE';

export const CALL_NOTE_ACTIVITY_REMOVE = 'CALL_NOTE_ACTIVITY_REMOVE';
export const CALL_NOTE_ACTIVITY_CHANGE = 'CALL_NOTE_ACTIVITY_CHANGE';
export const CALL_NOTE_CATEGORY_CHOOSE = 'CALL_NOTE_CATEGORY_CHOOSE';
export const CALL_NOTE_ACTIVITY_CHOOSE = 'CALL_NOTE_ACTIVITY_CHOOSE';

export const MOOD_IMAGES = fromPairs([
  [CALL_NOTES_MENTEE_HAPPY, images.CALL_NOTES_MENTEE_HAPPY],
  [CALL_NOTES_MENTEE_SAD, images.CALL_NOTES_MENTEE_SAD],
  [CALL_NOTES_MENTEE_BORED, images.CALL_NOTES_MENTEE_BORED],
  [CALL_NOTES_MENTEE_CONFUSED, images.CALL_NOTES_MENTEE_CONFUSED],
  [CALL_NOTES_MENTEE_UPSET, images.CALL_NOTES_MENTEE_UPSET],
  [CALL_NOTES_MENTEE_WITHDRAWN, images.CALL_NOTES_MENTEE_WITHDRAWN],
]);

export const EVENT_MOOD_IMAGES = fromPairs([
  [CALL_NOTES_MENTEE_HAPPY, images.EVENT_MENTEE_HAPPY],
  [CALL_NOTES_MENTEE_SAD, images.EVENT_MENTEE_SAD],
  [CALL_NOTES_MENTEE_BORED, images.EVENT_MENTEE_BORED],
  [CALL_NOTES_MENTEE_CONFUSED, images.EVENT_MENTEE_CONFUSED],
  [CALL_NOTES_MENTEE_UPSET, images.EVENT_MENTEE_UPSET],
  [CALL_NOTES_MENTEE_WITHDRAWN, images.EVENT_MENTEE_WITHDRAWN],
  [CALL_NOTES_MENTEE_EXCITED, images.EVENT_MENTEE_EXCITED],
  [CALL_NOTES_MENTEE_ENGAGED, images.EVENT_MENTEE_ENGAGED],
]);

export const CALL_QUALITY_EXCELLENT = 'EXCELLENT';
export const CALL_QUALITY_OK = 'OK';
export const CALL_QUALITY_INAUDIBLE = 'INAUDIBLE';
export const CALL_QUALITY_DROPPED = 'DROPPED';
export const CALL_QUALITY_DELAYED = 'DELAYED';

export const RATING_ITEMS = [
  'Not at all',
  'A little',
  'Somewhat',
  'Quite a bit',
  'A lot',
];

export const CALL_QUALITY_ITEMS = fromPairs([
  [CALL_QUALITY_EXCELLENT, 'Excellent'],
  [CALL_QUALITY_OK, 'Ok'],
  [CALL_QUALITY_INAUDIBLE, "Couldn't hear"],
  [CALL_QUALITY_DROPPED, 'Call dropped'],
  [CALL_QUALITY_DELAYED, 'Delays'],
]);

export const V2_MOOD_HAPPY = 'HAPPY';
export const V2_MOOD_SAD = 'SAD';
export const V2_MOOD_BORED = 'BORED';
export const V2_MOOD_CONFUSED = 'CONFUSED';
export const V2_MOOD_UPSET = 'UPSET';
export const V2_MOOD_WITHDRAWN = 'WITHDRAWN';
export const V2_MOOD_EXCITED = 'EXCITED';
export const V2_MOOD_ENGAGED = 'ENGAGED';

export const V2_MOOD_IMAGES = fromPairs([
  [V2_MOOD_HAPPY, images.CALL_NOTES_MENTEE_HAPPY],
  [V2_MOOD_SAD, images.CALL_NOTES_MENTEE_SAD],
  [V2_MOOD_BORED, images.CALL_NOTES_MENTEE_BORED],
  [V2_MOOD_CONFUSED, images.CALL_NOTES_MENTEE_CONFUSED],
  [V2_MOOD_UPSET, images.CALL_NOTES_MENTEE_UPSET],
  [V2_MOOD_WITHDRAWN, images.CALL_NOTES_MENTEE_WITHDRAWN],
  [V2_MOOD_EXCITED, images.CALL_NOTES_MENTEE_EXCITED],
  [V2_MOOD_ENGAGED, images.CALL_NOTES_MENTEE_ENGAGED],
]);

export const V2_EVENT_MOOD_IMAGES = fromPairs([
  [V2_MOOD_HAPPY, images.EVENT_MENTEE_HAPPY],
  [V2_MOOD_SAD, images.EVENT_MENTEE_SAD],
  [V2_MOOD_BORED, images.EVENT_MENTEE_BORED],
  [V2_MOOD_CONFUSED, images.EVENT_MENTEE_CONFUSED],
  [V2_MOOD_UPSET, images.EVENT_MENTEE_UPSET],
  [V2_MOOD_WITHDRAWN, images.EVENT_MENTEE_WITHDRAWN],
  [V2_MOOD_EXCITED, images.EVENT_MENTEE_EXCITED],
  [V2_MOOD_ENGAGED, images.EVENT_MENTEE_ENGAGED],
]);

export const V2_MOOD_LABELS = fromPairs([
  [V2_MOOD_HAPPY, 'Happy'],
  [V2_MOOD_SAD, 'Sad'],
  [V2_MOOD_BORED, 'Bored'],
  [V2_MOOD_CONFUSED, 'Confused'],
  [V2_MOOD_UPSET, 'Upset'],
  [V2_MOOD_WITHDRAWN, 'Withdrawn'],
  [V2_MOOD_EXCITED, 'Excited'],
  [V2_MOOD_ENGAGED, 'Engaged'],
]);

export const V2_STEP_BACK = 'V2_STEP_BACK';
export const V2_STEP_NEXT = 'V2_STEP_NEXT';

export const V2_STEP_CALL_RESULT = 'V2_STEP_CALL_RESULT';
export const V2_STEP_ACTIVITY_PROGRESS = 'V2_STEP_ACTIVITY_PROGRESS';
export const V2_STEP_OBJECTIVE_ACHIEVED = 'V2_STEP_OBJECTIVE_ACHIEVED';
export const V2_STEP_REFLECTION = 'V2_STEP_REFLECTION';
export const V2_STEP_RATING = 'V2_STEP_RATING';
export const V2_STEP_MOOD = 'V2_STEP_MOOD';
export const V2_STEP_CALL_QUALITY = 'V2_STEP_CALL_QUALITY';

export const V2_STEPS = [
  V2_STEP_CALL_RESULT,
  V2_STEP_ACTIVITY_PROGRESS,
  V2_STEP_OBJECTIVE_ACHIEVED,
  V2_STEP_RATING,
  V2_STEP_REFLECTION,
  V2_STEP_MOOD,
  V2_STEP_CALL_QUALITY,
];

export const V2_CALL_RESULT_COMPLETED = 'COMPLETED';
export const V2_CALL_RESULT_PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED';
export const V2_CALL_RESULT_MENTEE_NOT_AVAILABLE = 'MENTEE_NOT_AVAILABLE';
export const V2_CALL_RESULT_MENTEE_RESCHEDULED = 'MENTEE_RESCHEDULED';

export const V2_CALL_RESULT_ITEMS = [
  V2_CALL_RESULT_COMPLETED,
  V2_CALL_RESULT_PARTIALLY_COMPLETED,
  V2_CALL_RESULT_MENTEE_NOT_AVAILABLE,
  V2_CALL_RESULT_MENTEE_RESCHEDULED,
];

export const V2_OBJECTIVE_ACHIEVED_LABELS = {
  1: 'Objective was achieved',
  2: 'Mostly achieved',
  3: 'Somewhat achieved',
  4: 'Achieved a little',
  5: 'Not at all',
};

export const V2_RATING_LABELS = {
  1: 'Very good',
  2: 'Good',
  3: 'Average',
  4: 'Poor',
  5: 'Very Poor',
};

export const V2_CALL_QUALITY_LABELS = {
  1: 'Excellent',
  2: 'Ok',
  3: "Couldn't hear",
  4: 'Call dropped',
  5: 'Delays',
};

export const V2_ACTIVITY_USED = 'USED';
export const V2_ACTIVITY_COMPLETED = 'COMPLETED';
export const V2_ACTIVITY_PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED';
export const V2_ACTIVITY_NOT_USED = 'NOT_USED';
export const V2_ACTIVITY_DIFFERENT = 'DIFFERENT';
