const CALL_NOTE_LIST_REQUEST = 'CALL_NOTE_LIST_REQUEST';
const CALL_NOTE_LIST_SUCCESS = 'CALL_NOTE_LIST_SUCCESS';
const CALL_NOTE_LIST_FAILURE = 'CALL_NOTE_LIST_FAILURE';

const CALL_NOTE_CREATE_REQUEST = 'CALL_NOTE_CREATE_REQUEST';
const CALL_NOTE_CREATE_SUCCESS = 'CALL_NOTE_CREATE_SUCCESS';
const CALL_NOTE_CREATE_FAILURE = 'CALL_NOTE_CREATE_FAILURE';

const CALL_NOTE_UPDATE_REQUEST = 'CALL_NOTE_UPDATE_REQUEST';
const CALL_NOTE_UPDATE_SUCCESS = 'CALL_NOTE_UPDATE_SUCCESS';
const CALL_NOTE_UPDATE_FAILURE = 'CALL_NOTE_UPDATE_FAILURE';

const CALL_NOTE_PATCH_REQUEST = 'CALL_NOTE_PATCH_REQUEST';
const CALL_NOTE_PATCH_SUCCESS = 'CALL_NOTE_PATCH_SUCCESS';
const CALL_NOTE_PATCH_FAILURE = 'CALL_NOTE_PATCH_FAILURE';


const CALL_NOTES_MENTEE_HAPPY = 'happy';
const CALL_NOTES_MENTEE_SAD = 'sad';
const CALL_NOTES_MENTEE_BORED = 'bored';
const CALL_NOTES_MENTEE_CONFUSED = 'confused';
const CALL_NOTES_MENTEE_UPSET = 'upset';
const CALL_NOTES_MENTEE_WITHDRAWN = 'withdrawn';


export {
  CALL_NOTE_LIST_REQUEST,
  CALL_NOTE_LIST_SUCCESS,
  CALL_NOTE_LIST_FAILURE,

  CALL_NOTE_CREATE_REQUEST,
  CALL_NOTE_CREATE_SUCCESS,
  CALL_NOTE_CREATE_FAILURE,

  CALL_NOTE_UPDATE_REQUEST,
  CALL_NOTE_UPDATE_SUCCESS,
  CALL_NOTE_UPDATE_FAILURE,

  CALL_NOTE_PATCH_REQUEST,
  CALL_NOTE_PATCH_SUCCESS,
  CALL_NOTE_PATCH_FAILURE,

  CALL_NOTES_MENTEE_HAPPY,
  CALL_NOTES_MENTEE_SAD,
  CALL_NOTES_MENTEE_BORED,
  CALL_NOTES_MENTEE_CONFUSED,
  CALL_NOTES_MENTEE_UPSET,
  CALL_NOTES_MENTEE_WITHDRAWN,
};
