const CALL_NOTE_LIST_REQUEST = 'CALL_NOTE_LIST_REQUEST';
const CALL_NOTE_LIST_SUCCESS = 'CALL_NOTE_LIST_SUCCESS';
const CALL_NOTE_LIST_FAILURE = 'CALL_NOTE_LIST_FAILURE';

const CALL_NOTE_CREATE_REQUEST = 'CALL_NOTE_CREATE_REQUEST';
const CALL_NOTE_CREATE_SUCCESS = 'CALL_NOTE_CREATE_SUCCESS';
const CALL_NOTE_CREATE_FAILURE = 'CALL_NOTE_CREATE_FAILURE';

const CALL_NOTE_UPDATE_REQUEST = 'CALL_NOTE_UPDATE_REQUEST';
const CALL_NOTE_UPDATE_SUCCESS = 'CALL_NOTE_UPDATE_SUCCESS';
const CALL_NOTE_UPDATE_FAILURE = 'CALL_NOTE_UPDATE_FAILURE';

const CALL_NOTE_PATCH_REQUEST = 'CALL_NOTE_PATCH_REQUEST';
const CALL_NOTE_PATCH_SUCCESS = 'CALL_NOTE_PATCH_SUCCESS';
const CALL_NOTE_PATCH_FAILURE = 'CALL_NOTE_PATCH_FAILURE';


export {
  CALL_NOTE_LIST_REQUEST,
  CALL_NOTE_LIST_SUCCESS,
  CALL_NOTE_LIST_FAILURE,

  CALL_NOTE_CREATE_REQUEST,
  CALL_NOTE_CREATE_SUCCESS,
  CALL_NOTE_CREATE_FAILURE,

  CALL_NOTE_UPDATE_REQUEST,
  CALL_NOTE_UPDATE_SUCCESS,
  CALL_NOTE_UPDATE_FAILURE,

  CALL_NOTE_PATCH_REQUEST,
  CALL_NOTE_PATCH_SUCCESS,
  CALL_NOTE_PATCH_FAILURE,
};
