export const STEP_CALL_RESULT = 'STEP_CALL_RESULT';
export const STEP_UNPLANNED_ACTIVITY_CHECK = 'STEP_UNPLANNED_ACTIVITY_CHECK';
export const STEP_PLANNED_ACTIVITY_PROGRESS = 'STEP_PLANNED_ACTIVITY_PROGRESS';
export const STEP_UNPLANNED_ACTIVITY_PROGRESS = 'STEP_PLANNED_ACTIVITY_PROGRESS';
export const STEP_OBJECTIVE_ACHIEVED = 'STEP_OBJECTIVE_ACHIEVED';
export const STEP_REFLECTION = 'STEP_REFLECTION';
export const STEP_RATING = 'STEP_RATING';
export const STEP_MOOD = 'STEP_MOOD';
export const STEP_CALL_QUALITY = 'STEP_CALL_QUALITY';


export const STEPS_NO_ACTIVITY = [
  STEP_CALL_RESULT,
  STEP_UNPLANNED_ACTIVITY_CHECK,
  STEP_UNPLANNED_ACTIVITY_PROGRESS,
  STEP_OBJECTIVE_ACHIEVED,
  STEP_REFLECTION,
  STEP_RATING,
  STEP_MOOD,
  STEP_CALL_QUALITY,
];


export const STEPS_ACTIVITY = [
  STEP_CALL_RESULT,
  STEP_PLANNED_ACTIVITY_PROGRESS,
  STEP_UNPLANNED_ACTIVITY_PROGRESS,
  STEP_OBJECTIVE_ACHIEVED,
  STEP_REFLECTION,
  STEP_RATING,
  STEP_MOOD,
  STEP_CALL_QUALITY,
];
