const NEW_USER_ENTER = 'NEW_USER_ENTER';
const EXISTING_USER_ENTER_REQUEST = 'EXISTING_USER_ENTER_REQUEST';
const EXISTING_USER_ENTER_SUCCESS = 'EXISTING_USER_ENTER_SUCCESS';
const EXISTING_USER_ENTER_FAILURE = 'EXISTING_USER_ENTER_FAILURE';


export {
  NEW_USER_ENTER,
  EXISTING_USER_ENTER_REQUEST,
  EXISTING_USER_ENTER_SUCCESS,
  EXISTING_USER_ENTER_FAILURE,
};
