const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST';
const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE';


export {
  EVENT_LIST_REQUEST,
  EVENT_LIST_SUCCESS,
  EVENT_LIST_FAILURE,
};
