import { fromPairs } from 'lodash';


const EVENT_POLL_INTERVAL = 1000 * 60 * 2;
const EVENT_POLL_TICK = 'EVENT_POLL_TICK';

const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST';
const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
const EVENT_LIST_FAILURE = 'EVENT_LIST_FAILURE';
const EVENT_LIST_NETWORK_FAILURE = 'EVENT_LIST_NETWORK_FAILURE';

const EVENT_LIST_RECENT_PAGE_SIZE = 20;

const EVENT_TYPE_SCHEDULED_CALL_CREATED = 'call_scheduled';
const EVENT_TYPE_SCHEDULED_CALL_UPDATED = 'schedule_changed';
const EVENT_TYPE_SCHEDULED_CALL_CANCELLED = 'schedule_cancelled';
const EVENT_TYPE_CALL_STARTED = 'start_call';
const EVENT_TYPE_CALL_ENDED = 'end_call';
const EVENT_TYPE_MESSAGE_SENT = 'send_message';
const EVENT_TYPE_MESSAGE_RECEIVED = 'receive_message';
const EVENT_TYPE_ACTIVITIY_CATEGORY_COMPLETED = 'all_activities_completed';
const EVENT_TYPE_CALL_NOTES_CREATED = 'call_notes_created';

const TYPES_TO_COLLECTIONS = fromPairs([
  [EVENT_TYPE_SCHEDULED_CALL_CREATED, 'scheduledCalls'],
  [EVENT_TYPE_ACTIVITIY_CATEGORY_COMPLETED, 'categories'],
  [EVENT_TYPE_CALL_NOTES_CREATED, 'callNotes'],
  [EVENT_TYPE_MESSAGE_RECEIVED, 'messages'],
]);


const COLLAPSIBLE_EVENTS = [
  EVENT_TYPE_MESSAGE_RECEIVED,
];


export {
  EVENT_POLL_TICK,
  EVENT_POLL_INTERVAL,

  EVENT_LIST_RECENT_PAGE_SIZE,

  EVENT_LIST_REQUEST,
  EVENT_LIST_SUCCESS,
  EVENT_LIST_FAILURE,
  EVENT_LIST_NETWORK_FAILURE,

  EVENT_TYPE_SCHEDULED_CALL_CREATED,
  EVENT_TYPE_SCHEDULED_CALL_UPDATED,
  EVENT_TYPE_SCHEDULED_CALL_CANCELLED,
  EVENT_TYPE_CALL_STARTED,
  EVENT_TYPE_CALL_ENDED,
  EVENT_TYPE_MESSAGE_SENT,
  EVENT_TYPE_MESSAGE_RECEIVED,
  EVENT_TYPE_ACTIVITIY_CATEGORY_COMPLETED,
  EVENT_TYPE_CALL_NOTES_CREATED,

  TYPES_TO_COLLECTIONS,
  COLLAPSIBLE_EVENTS,
};
