export const FORGOT_PASSWORD_EMAIL_REQUEST = 'FORGOT_PASSWORD_EMAIL_REQUEST';
export const FORGOT_PASSWORD_EMAIL_SUCCESS = 'FORGOT_PASSWORD_EMAIL_SUCCESS';

export const FORGOT_PASSWORD_RESET_REQUEST = 'FORGOT_PASSWORD_RESET_REQUEST';
export const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS';
export const FORGOT_PASSWORD_RESET_BAD_TOKEN = 'FORGOT_PASSWORD_RESET_BAD_TOKEN';
