export const FORGOT_PASSWORD_SEND_EMAIL_REQUEST = 'FORGOT_PASSWORD_SEND_EMAIL_REQUEST';
export const FORGOT_PASSWORD_SEND_EMAIL_SUCCESS = 'FORGOT_PASSWORD_SEND_EMAIL_SUCCESS';
export const FORGOT_PASSWORD_SEND_EMAIL_BAD_ADDRESS = 'FORGOT_PASSWORD_SEND_EMAIL_BAD_ADDRESS';

export const FORGOT_PASSWORD_RESET_REQUEST = 'FORGOT_PASSWORD_RESET_REQUEST';
export const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS';
export const FORGOT_PASSWORD_RESET_BAD_TOKEN = 'FORGOT_PASSWORD_RESET_BAD_TOKEN';

export const SHOW_FORGOT_PASSWORD_EMAIL = 'SHOW_FORGOT_PASSWORD_EMAIL';
export const SHOW_FORGOT_PASSWORD_RESET = 'SHOW_FORGOT_PASSWORD_RESET';
export const RESET_TO_LOGIN_SCREEN = 'RESET_TO_LOGIN_SCREEN';

export const FORGOT_PASSWORD_EMAIL_STATUS_IDLE = 'FORGOT_PASSWORD_EMAIL_STATUS_IDLE';
export const FORGOT_PASSWORD_EMAIL_STATUS_BUSY = 'FORGOT_PASSWORD_EMAIL_STATUS_BUSY';
export const FORGOT_PASSWORD_EMAIL_STATUS_BAD_ADDRESS = 'FORGOT_PASSWORD_EMAIL_STATUS_BAD_ADDRESS';

export const FORGOT_PASSWORD_RESET_STATUS_IDLE = 'FORGOT_PASSWORD_RESET_STATUS_IDLE';
export const FORGOT_PASSWORD_RESET_STATUS_BUSY = 'FORGOT_PASSWORD_RESET_STATUS_BUSY';
export const FORGOT_PASSWORD_RESET_STATUS_BAD_TOKEN = 'FORGOT_PASSWORD_RESET_STATUS_BAD_TOKEN';
