const FORGOT_PASSWORD_EMAIL_REQUEST = 'FORGOT_PASSWORD_EMAIL_REQUEST';
const FORGOT_PASSWORD_EMAIL_SUCCESS = 'FORGOT_PASSWORD_EMAIL_SUCCESS';

const FORGOT_PASSWORD_RESET_REQUEST = 'FORGOT_PASSWORD_RESET_REQUEST';
const FORGOT_PASSWORD_RESET_SUCCESS = 'FORGOT_PASSWORD_RESET_SUCCESS';
const FORGOT_PASSWORD_RESET_BAD_TOKEN = 'FORGOT_PASSWORD_RESET_BAD_TOKEN';
