// TODO rename these to not include request
const NAVIGATE_BACK_REQUEST = 'NAVIGATE_BACK_REQUEST';
const NAVIGATE_FORWARD_REQUEST = 'NAVIGATE_FORWARD_REQUEST';
const SCREEN_DISMISS = 'SCREEN_DISMISS';

const NAV_TAB_ACTIVITIES = 'NAV_TAB_ACTIVITIES';
const NAV_TAB_CHAT = 'NAV_TAB_CHAT';
const NAV_TAB_COMMUNITY = 'NAV_TAB_COMMUNITY';
const NAV_TAB_JOURNEY = 'NAV_TAB_JOURNEY';
const NAV_TAB_SCHEDULED_CALLS = 'NAV_TAB_SCHEDULED_CALLS';


export {
  NAVIGATE_BACK_REQUEST,
  NAVIGATE_FORWARD_REQUEST,
  SCREEN_DISMISS,

  NAV_TAB_ACTIVITIES,
  NAV_TAB_CHAT,
  NAV_TAB_COMMUNITY,
  NAV_TAB_JOURNEY,
  NAV_TAB_SCHEDULED_CALLS,
};
