// TODO rename these to not include request
const NAVIGATE_BACK_REQUEST = 'NAVIGATE_BACK_REQUEST';
const NAVIGATE_FORWARD_REQUEST = 'NAVIGATE_FORWARD_REQUEST';

const SCREEN_DISMISS = 'SCREEN_DISMISS';


export {
  NAVIGATE_BACK_REQUEST,
  NAVIGATE_FORWARD_REQUEST,
  SCREEN_DISMISS,
};
