export const NOTIFICATION_ACTIONS = {
  CALL_STARTING_HOUR: 'CALL_STARTING_HOUR_NOTIFICATION_RECEIVED',
  CALL_STARTING_10_MIN: 'CALL_STARTING_10_MIN_NOTIFICATION_RECEIVED',
  CALL_STARTING_1_MIN: 'CALL_STARTING_1_MIN_NOTIFICATION_RECEIVED',
  CALL_ENDED: 'CALL_ENDED_NOTIFICATION_RECEIVED',
  DUMMY: 'DUMMY_NOTIFICATION_RECEIVED',
};


export const NOTIFICATIONS_SETUP_FAILURE = 'NOTIFICATIONS_SETUP_FAILURE';
export const UNKNOWN_NOTIFICATION_ACTION = 'UNKNOWN_NOTIFICATION_RECEIVED';
