export const UPDATE_NOTIFICATION_TOKEN_SUCCESS = 'UPDATE_NOTIFICATION_TOKEN_SUCCESS';
export const UPDATE_NOTIFICATION_TOKEN_REQUEST = 'UPDATE_NOTIFICATION_TOKEN_REQUEST';
export const UPDATE_NOTIFICATION_TOKEN_FAILURE = 'UPDATE_NOTIFICATION_TOKEN_FAILURE';
