export const CALL_STARTING_HOUR_RECEIVED = 'CALL_STARTING_HOUR_RECEIVED';
export const CALL_STARTING_10_MIN_RECEIVED = 'CALL_STARTING_10_MIN_RECEIVED';
export const CALL_STARTING_1_MIN_RECEIVED = 'CALL_STARTING_1_MIN_RECEIVED';
export const CALL_ENDED_RECEIVED = 'CALL_ENDED_RECEIVED';
export const DUMMY_RECEIVED = 'DUMMY_RECEIVED';


export const NOTIFICATIONS_SETUP_FAILURE = 'NOTIFICATIONS_SETUP_FAILURE';
export const UNKNOWN_ACTION = 'UNKNOWN_RECEIVED';


export const NOTIFICATION_ACTIONS = {
  CALL_STARTING_HOUR: CALL_STARTING_HOUR_RECEIVED,
  CALL_STARTING_10_MIN: CALL_STARTING_10_MIN_RECEIVED,
  CALL_STARTING_1_MIN: CALL_STARTING_1_MIN_RECEIVED,
  CALL_ENDED: CALL_ENDED_RECEIVED,
  DUMMY: DUMMY_RECEIVED,
};
