const ONBOARDING_CHOOSE_PROFILE_PICTURE = 'ONBOARDING_CHOOSE_PROFILE_PICTURE';
const ONBOARDING_CHANGE_PROFILE_PICTURE = 'ONBOARDING_CHANGE_PROFILE_PICTURE';
const ONBOARDING_CHANGE_PROFILE = 'ONBOARDING_CHANGE_PROFILE';

const ONBOARDING_STEP_BACK_REQUEST = 'ONBOARDING_BACK_REQUEST';
const ONBOARDING_STEP_FORWARD_REQUEST = 'ONBOARDING_NEXT_REQUEST';

const ONBOARDING_UPDATE_PROFILE_REQUEST = 'ONBOARDING_UPDATE_PROFILE_REQUEST';
const ONBOARDING_UPDATE_PROFILE_SUCCESS = 'ONBOARDING_UPDATE_PROFILE_SUCCESS';
const ONBOARDING_UPDATE_PROFILE_FAILURE = 'ONBOARDING_UPDATE_PROFILE_FAILURE';

const ONBOARDING_UPDATE_IMAGE_REQUEST = 'ONBOARDING_UPDATE_IMAGE_REQUEST';
const ONBOARDING_UPDATE_IMAGE_SUCCESS = 'ONBOARDING_UPDATE_IMAGE_SUCCESS';
const ONBOARDING_UPDATE_IMAGE_FAILURE = 'ONBOARDING_UPDATE_IMAGE_FAILURE';

const ONBOARDING_STATUS_IDLE = 'STATUS_IDLE';
const ONBOARDING_STATUS_BUSY = 'STATUS_BUSY';
const ONBOARDING_STATUS_ERROR = 'STATUS_ERROR';


export {
  ONBOARDING_CHOOSE_PROFILE_PICTURE,
  ONBOARDING_CHANGE_PROFILE_PICTURE,
  ONBOARDING_CHANGE_PROFILE,

  ONBOARDING_STEP_BACK_REQUEST,
  ONBOARDING_STEP_FORWARD_REQUEST,

  ONBOARDING_UPDATE_PROFILE_REQUEST,
  ONBOARDING_UPDATE_PROFILE_SUCCESS,
  ONBOARDING_UPDATE_PROFILE_FAILURE,

  ONBOARDING_UPDATE_IMAGE_REQUEST,
  ONBOARDING_UPDATE_IMAGE_SUCCESS,
  ONBOARDING_UPDATE_IMAGE_FAILURE,

  ONBOARDING_STATUS_IDLE,
  ONBOARDING_STATUS_BUSY,
  ONBOARDING_STATUS_ERROR,
};
