const ONBOARDING_CHANGE_PICTURE = 'ONBOARDING_CHANGE_PICTURE';
const ONBOARDING_CHANGE_PROFILE = 'ONBOARDING_CHANGE_PROFILE';

const ONBOARDING_SETUP_PROFILE_REQUEST = 'ONBOARDING_SETUP_PROFILE_REQUEST';
const ONBOARDING_SETUP_PROFILE_SUCCESS = 'ONBOARDING_SETUP_PROFILE_SUCCESS';
const ONBOARDING_SETUP_PROFILE_FAILURE = 'ONBOARDING_SETUP_PROFILE_FAILURE';

const ONBOARDING_STATUS_IDLE = 'STATUS_IDLE';
const ONBOARDING_STATUS_BUSY = 'STATUS_BUSY';
const ONBOARDING_STATUS_ERROR = 'STATUS_ERROR';

const ONBOARDING_OPEN_PICTURE_PICKER = 'ONBOARDING_OPEN_PICTURE_PICKER';
const ONBOARDING_PICTURE_CHOSEN = 'ONBOARDING_PICTURE_CHOSEN';


export {
  ONBOARDING_CHANGE_PICTURE,
  ONBOARDING_CHANGE_PROFILE,

  ONBOARDING_SETUP_PROFILE_REQUEST,
  ONBOARDING_SETUP_PROFILE_SUCCESS,
  ONBOARDING_SETUP_PROFILE_FAILURE,

  ONBOARDING_STATUS_IDLE,
  ONBOARDING_STATUS_BUSY,
  ONBOARDING_STATUS_ERROR,

  ONBOARDING_OPEN_PICTURE_PICKER,
  ONBOARDING_PICTURE_CHOSEN,
};
