const ONBOARDING_START_PROFILE = 'ONBOARDING_START_PROFILE';
const ONBOARDING_CHOOSE_PROFILE_PICTURE = 'ONBOARDING_CHOOSE_PROFILE_PICTURE';

const ONBOARDING_UPDATE_PROFILE_PICTURE = 'ONBOARDING_UPDATE_PROFILE_PICTURE';
const ONBOARDING_UPDATE_PROFILE = 'ONBOARDING_UPDATE_PROFILE';

const ONBOARDING_OCCUPATION_NEXT = 'ONBOARDING_OCCUPATION_NEXT';


export {
  ONBOARDING_START_PROFILE,
  ONBOARDING_CHOOSE_PROFILE_PICTURE,

  ONBOARDING_UPDATE_PROFILE_PICTURE,
  ONBOARDING_UPDATE_PROFILE,

  ONBOARDING_OCCUPATION_NEXT,
};
