const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';

const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

const PROFILE_IMAGE_UPDATE_REQUEST = 'PROFILE_IMAGE_UPDATE_REQUEST';
const PROFILE_IMAGE_UPDATE_SUCCESS = 'PROFILE_IMAGE_UPDATE_SUCCESS';
const PROFILE_IMAGE_UPDATE_FAILURE = 'PROFILE_IMAGE_UPDATE_FAILURE';

const PROFILE_OPEN = 'PROFILE_OPEN';

const PROFILE_STATUS_IDLE = 'STATUS_IDLE';
const PROFILE_STATUS_BUSY = 'STATUS_BUSY';
const PROFILE_STATUS_ERROR = 'STATUS_ERROR';


export {
  PROFILE_FETCH_REQUEST,
  PROFILE_FETCH_SUCCESS,
  PROFILE_FETCH_FAILURE,

  PROFILE_UPDATE_REQUEST,
  PROFILE_UPDATE_SUCCESS,
  PROFILE_UPDATE_FAILURE,

  PROFILE_IMAGE_UPDATE_REQUEST,
  PROFILE_IMAGE_UPDATE_SUCCESS,
  PROFILE_IMAGE_UPDATE_FAILURE,

  PROFILE_OPEN,

  PROFILE_STATUS_IDLE,
  PROFILE_STATUS_BUSY,
  PROFILE_STATUS_ERROR,
};
