const ROUTE_LANDING = 'ROUTE_LANDING';

const ROUTE_AUTH_LOGIN = 'ROUTE_AUTH_LOGIN';
const ROUTE_AUTH_ACTIVATION = 'ROUTE_AUTH_ACTIVATION';
const ROUTE_AUTH_RESET_PASSWORD = 'ROUTE_AUTH_RESET_PASSWORD';

const ROUTE_ONBOARDING_WELCOME = 'ROUTE_ONBOARDING_WELCOME';
const ROUTE_ONBOARDING_PROFILE_PICTURE = 'ROUTE_ONBOARDING_PROFILE_PICTURE';
const ROUTE_ONBOARDING_CAMERA_ROLL = 'ROUTE_ONBOARDING_CAMERA_ROLL';
const ROUTE_ONBOARDING_OCCUPATION = 'ROUTE_ONBOARDING_OCCUPATION';
const ROUTE_ONBOARDING_MOTIVATION = 'ROUTE_ONBOARDING_MOTIVATION';
const ROUTE_ONBOARDING_OWN_MENTOR = 'ROUTE_ONBOARDING_OWN_MENTOR';
const ROUTE_ONBOARDING_THREE_WORDS = 'ROUTE_ONBOARDING_THREE_WORDS';
const ROUTE_ONBOARDING_SKILLS = 'ROUTE_ONBOARDING_SKILLS';

const ROUTE_LOADING = 'ROUTE_LOADING';
const ROUTE_JOURNEY = 'ROUTE_JOURNEY';

const ROUTE_CATEGORY_LIST = 'ROUTE_CATEGORY_LIST';
const ROUTE_CATEGORY = 'ROUTE_CATEGORY';
const ROUTE_ACTIVITY = 'ROUTE_ACTIVITY';

const ROUTE_SCHEDULE_CALL = 'ROUTE_SCHEDULE_CALL';


const ONBOARDING_STEPS = [
  ROUTE_ONBOARDING_PROFILE_PICTURE,
  ROUTE_ONBOARDING_OCCUPATION,
  ROUTE_ONBOARDING_MOTIVATION,
  ROUTE_ONBOARDING_OWN_MENTOR,
  ROUTE_ONBOARDING_THREE_WORDS,
  ROUTE_ONBOARDING_SKILLS,
];


export {
  ROUTE_LANDING,

  ROUTE_AUTH_LOGIN,
  ROUTE_AUTH_ACTIVATION,
  ROUTE_AUTH_RESET_PASSWORD,

  ROUTE_ONBOARDING_WELCOME,
  ROUTE_ONBOARDING_PROFILE_PICTURE,
  ROUTE_ONBOARDING_CAMERA_ROLL,
  ROUTE_ONBOARDING_OCCUPATION,
  ROUTE_ONBOARDING_MOTIVATION,
  ROUTE_ONBOARDING_OWN_MENTOR,
  ROUTE_ONBOARDING_THREE_WORDS,
  ROUTE_ONBOARDING_SKILLS,

  ROUTE_LOADING,
  ROUTE_JOURNEY,

  ROUTE_CATEGORY_LIST,
  ROUTE_CATEGORY,
  ROUTE_ACTIVITY,

  ROUTE_SCHEDULE_CALL,

  ONBOARDING_STEPS,
};
