const ROUTE_LANDING = 'ROUTE_LANDING';

const ROUTE_AUTH_LOGIN = 'ROUTE_AUTH_LOGIN';
const ROUTE_AUTH_ACTIVATION = 'ROUTE_AUTH_ACTIVATION';
const ROUTE_AUTH_RESET_PASSWORD = 'ROUTE_AUTH_RESET_PASSWORD';

const ROUTE_ONBOARDING = 'ROUTE_ONBOARDING';
const ROUTE_ONBOARDING_CAMERA_ROLL = 'ROUTE_ONBOARDING_CAMERA_ROLL';

const ROUTE_LOADING = 'ROUTE_LOADING';
const ROUTE_JOURNEY = 'ROUTE_JOURNEY';

const ROUTE_CATEGORY_LIST = 'ROUTE_CATEGORY_LIST';
const ROUTE_CATEGORY = 'ROUTE_CATEGORY';
const ROUTE_ACTIVITY = 'ROUTE_ACTIVITY';

const ROUTE_SCHEDULE_CALL = 'ROUTE_SCHEDULE_CALL';

const STACK_LANDING = 'ROUTES_LANDING';
const STACK_ACTIVITIES = 'ROUTES_ACTIVITIES';
const STACK_ONBOARDING = 'ROUTES_ONBOARDING';
const STACK_JOURNEY = 'ROUTES_JOURNEY';

export {
  ROUTE_LANDING,

  ROUTE_AUTH_LOGIN,
  ROUTE_AUTH_ACTIVATION,
  ROUTE_AUTH_RESET_PASSWORD,

  ROUTE_ONBOARDING,
  ROUTE_ONBOARDING_CAMERA_ROLL,

  ROUTE_LOADING,
  ROUTE_JOURNEY,

  ROUTE_CATEGORY_LIST,
  ROUTE_CATEGORY,
  ROUTE_ACTIVITY,

  ROUTE_SCHEDULE_CALL,

  STACK_LANDING,
  STACK_ACTIVITIES,
  STACK_ONBOARDING,
  STACK_JOURNEY,
};
