const ROUTE_LANDING = 'ROUTE_LANDING';

const ROUTE_AUTH_LOGIN = 'ROUTE_AUTH_LOGIN';
const ROUTE_AUTH_ACTIVATION = 'ROUTE_AUTH_ACTIVATION';
const ROUTE_AUTH_RESET_PASSWORD = 'ROUTE_AUTH_RESET_PASSWORD';

const ROUTE_ONBOARDING = 'ROUTE_ONBOARDING';
const ROUTE_ONBOARDING_CAMERA_ROLL = 'ROUTE_ONBOARDING_CAMERA_ROLL';

const ROUTE_LOADING = 'ROUTE_LOADING';
const ROUTE_LOADING_FAILURE = 'ROUTE_LOADING_FAILURE';

const ROUTE_NAVIGATOR = 'ROUTE_NAVIGATOR';

const ROUTE_JOURNEY = 'ROUTE_JOURNEY';

const ROUTE_CATEGORY_LIST = 'ROUTE_CATEGORY_LIST';
const ROUTE_CATEGORY = 'ROUTE_CATEGORY';
const ROUTE_ACTIVITY = 'ROUTE_ACTIVITY';

const ROUTE_SCHEDULE_CALL = 'ROUTE_SCHEDULE_CALL';
const ROUTE_SCHEDULED_CALLS = 'ROUTE_SCHEDULED_CALLS';

const ROUTE_START_CALL = 'ROUTE_START_CALL';
const ROUTE_CONNECTING_CALL = 'ROUTE_CONNECTING_CALL';

const STACK_LANDING = 'STACK_LANDING';
const STACK_ACTIVITIES = 'STACK_ACTIVITIES';
const STACK_ONBOARDING = 'STACK_ONBOARDING';
const STACK_JOURNEY = 'STACK_JOURNEY';
const STACK_SCHEDULED_CALLS = 'STACK_SCHEDULED_CALLS';


export {
  ROUTE_LANDING,

  ROUTE_AUTH_LOGIN,
  ROUTE_AUTH_ACTIVATION,
  ROUTE_AUTH_RESET_PASSWORD,

  ROUTE_ONBOARDING,
  ROUTE_ONBOARDING_CAMERA_ROLL,

  ROUTE_LOADING,
  ROUTE_LOADING_FAILURE,

  ROUTE_NAVIGATOR,

  ROUTE_JOURNEY,

  ROUTE_CATEGORY_LIST,
  ROUTE_CATEGORY,
  ROUTE_ACTIVITY,

  ROUTE_SCHEDULE_CALL,
  ROUTE_SCHEDULED_CALLS,

  STACK_LANDING,
  STACK_ACTIVITIES,
  STACK_ONBOARDING,
  STACK_JOURNEY,
  STACK_SCHEDULED_CALLS,

  ROUTE_START_CALL,
  ROUTE_CONNECTING_CALL,
};
