const SCHEDULED_CALL_LIST_REQUEST = 'SCHEDULED_CALL_LIST_REQUEST';
const SCHEDULED_CALL_LIST_SUCCESS = 'SCHEDULED_CALL_LIST_SUCCESS';
const SCHEDULED_CALL_LIST_FAILURE = 'SCHEDULED_CALL_LIST_FAILURE';

const SCHEDULED_CALL_FETCH_REQUEST = 'SCHEDULED_CALL_FETCH_REQUEST';
const SCHEDULED_CALL_FETCH_SUCCESS = 'SCHEDULED_CALL_FETCH_SUCCESS';
const SCHEDULED_CALL_FETCH_FAILURE = 'SCHEDULED_CALL_FETCH_FAILURE';

const SCHEDULED_CALL_CREATE_REQUEST = 'SCHEDULED_CALL_CREATE_REQUEST';
const SCHEDULED_CALL_CREATE_SUCCESS = 'SCHEDULED_CALL_CREATE_SUCCESS';
const SCHEDULED_CALL_CREATE_FAILURE = 'SCHEDULED_CALL_CREATE_FAILURE';

const SCHEDULED_CALL_UPDATE_REQUEST = 'SCHEDULED_CALL_UPDATE_REQUEST';
const SCHEDULED_CALL_UPDATE_SUCCESS = 'SCHEDULED_CALL_UPDATE_SUCCESS';
const SCHEDULED_CALL_UPDATE_FAILURE = 'SCHEDULED_CALL_UPDATE_FAILURE';

const SCHEDULED_CALL_PATCH_REQUEST = 'SCHEDULED_CALL_PATCH_REQUEST';
const SCHEDULED_CALL_PATCH_SUCCESS = 'SCHEDULED_CALL_PATCH_SUCCESS';
const SCHEDULED_CALL_PATCH_FAILURE = 'SCHEDULED_CALL_PATCH_FAILURE';

const SCHEDULED_CALL_REMOVE_REQUEST = 'SCHEDULED_CALL_REMOVE_REQUEST';
const SCHEDULED_CALL_REMOVE_SUCCESS = 'SCHEDULED_CALL_REMOVE_SUCCESS';
const SCHEDULED_CALL_REMOVE_FAILURE = 'SCHEDULED_CALL_REMOVE_FAILURE';

const SCHEDULED_CALL_ADD = 'SCHEDULED_CALL_ADD';
const SCHEDULED_CALL_ADD_NEXT = 'SCHEDULED_CALL_ADD_NEXT';
const SCHEDULED_CALL_OPEN = 'SCHEDULED_CALL_OPEN';

const SCHEDULED_CALL_ACTIVITY_CHANGE = 'SCHEDULED_CALL_ACTIVITY_CHANGE';
const SCHEDULED_CALL_ACTIVITY_REMOVE = 'SCHEDULED_CALL_ACTIVITY_REMOVE';
const SCHEDULED_CALL_CATEGORY_CHOOSE = 'SCHEDULED_CALL_CATEGORY_CHOOSE';
const SCHEDULED_CALL_ACTIVITY_CHOOSE = 'SCHEDULED_CALL_ACTIVITY_CHOOSE';

const SCHEDULED_CALL_START = 'SCHEDULED_CALL_START';

const HOUR_MILLISECONDS = 1000 * 60 * 60;
const START_CALL_RANGE_START = HOUR_MILLISECONDS;
const START_CALL_RANGE_END = HOUR_MILLISECONDS;


export {
  SCHEDULED_CALL_LIST_REQUEST,
  SCHEDULED_CALL_LIST_SUCCESS,
  SCHEDULED_CALL_LIST_FAILURE,

  SCHEDULED_CALL_FETCH_REQUEST,
  SCHEDULED_CALL_FETCH_SUCCESS,
  SCHEDULED_CALL_FETCH_FAILURE,

  SCHEDULED_CALL_CREATE_REQUEST,
  SCHEDULED_CALL_CREATE_SUCCESS,
  SCHEDULED_CALL_CREATE_FAILURE,

  SCHEDULED_CALL_UPDATE_REQUEST,
  SCHEDULED_CALL_UPDATE_SUCCESS,
  SCHEDULED_CALL_UPDATE_FAILURE,

  SCHEDULED_CALL_PATCH_REQUEST,
  SCHEDULED_CALL_PATCH_SUCCESS,
  SCHEDULED_CALL_PATCH_FAILURE,

  SCHEDULED_CALL_REMOVE_REQUEST,
  SCHEDULED_CALL_REMOVE_SUCCESS,
  SCHEDULED_CALL_REMOVE_FAILURE,

  SCHEDULED_CALL_ADD,
  SCHEDULED_CALL_ADD_NEXT,
  SCHEDULED_CALL_OPEN,

  SCHEDULED_CALL_ACTIVITY_CHANGE,
  SCHEDULED_CALL_ACTIVITY_REMOVE,
  SCHEDULED_CALL_CATEGORY_CHOOSE,
  SCHEDULED_CALL_ACTIVITY_CHOOSE,

  SCHEDULED_CALL_START,

  START_CALL_RANGE_START,
  START_CALL_RANGE_END,
};
