
const NAVIGATION_AUTH_POP = 'NAVIGATION_AUTH_POP';
const NAVIGATION_AUTH_PUSH = 'NAVIGATION_AUTH_PUSH';

const ROUTE_AUTH_LANDING = 'ROUTE_LANDING';
const ROUTE_AUTH_LOGIN = 'ROUTE_AUTH_LOGIN';
const ROUTE_AUTH_ACTIVATE = 'ROUTE_AUTH_ACTIVATE';
const ROUTE_AUTH_RESET_PASSWORD = 'ROUTE_AUTH_RESET_PASSWORD';

export {
  NAVIGATION_AUTH_PUSH,
  NAVIGATION_AUTH_POP,
  ROUTE_AUTH_LANDING,
  ROUTE_AUTH_LOGIN,
  ROUTE_AUTH_ACTIVATE,
  ROUTE_AUTH_RESET_PASSWORD,
};
