const AUTH_NAVIGATION_POP = 'AUTH_NAVIGATION_POP';
const AUTH_NAVIGATION_PUSH = 'AUTH_NAVIGATION_PUSH';

const AUTH_ROUTE_LANDING = 'ROUTE_LANDING';
const AUTH_ROUTE_LOGIN = 'AUTH_ROUTE_LOGIN';
const AUTH_ROUTE_ACTIVATE = 'AUTH_ROUTE_ACTIVATE';
const AUTH_ROUTE_RESET_PASSWORD = 'AUTH_ROUTE_RESET_PASSWORD';

export {
  AUTH_NAVIGATION_PUSH,
  AUTH_NAVIGATION_POP,

  AUTH_ROUTE_LANDING,
  AUTH_ROUTE_LOGIN,
  AUTH_ROUTE_ACTIVATE,
  AUTH_ROUTE_RESET_PASSWORD,
};
