const PROFILE_IMAGE_UPDATE_REQUEST = 'PROFILE_IMAGE_UPDATE_REQUEST';
const PROFILE_IMAGE_UPDATE_SUCCESS = 'PROFILE_IMAGE_UPDATE_SUCCESS';
const PROFILE_IMAGE_UPDATE_FAILURE = 'PROFILE_IMAGE_UPDATE_FAILURE';

const PROFILE_FETCH_REQUEST = 'PROFILE_FETCH_REQUEST';
const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
const PROFILE_FETCH_FAILURE = 'PROFILE_FETCH_FAILURE';


export {
  PROFILE_IMAGE_UPDATE_REQUEST,
  PROFILE_IMAGE_UPDATE_SUCCESS,
  PROFILE_IMAGE_UPDATE_FAILURE,

  PROFILE_FETCH_REQUEST,
  PROFILE_FETCH_SUCCESS,
  PROFILE_FETCH_FAILURE,
};
