const PROFILE_IMAGE_UPDATE_REQUEST = 'PROFILE_IMAGE_UPDATE_REQUEST';
const PROFILE_IMAGE_UPDATE_SUCCESS = 'PROFILE_IMAGE_UPDATE_SUCCESS';
const PROFILE_IMAGE_UPDATE_FAILURE = 'PROFILE_IMAGE_UPDATE_FAILURE';


export {
  PROFILE_IMAGE_UPDATE_REQUEST,
  PROFILE_IMAGE_UPDATE_SUCCESS,
  PROFILE_IMAGE_UPDATE_FAILURE,
};
