const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
const AUTH_LOGIN_BUSY = 'AUTH_LOGIN_BUSY';
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
const AUTH_PASSWORD_RESET_BUSY = 'AUTH_PASSWORD_RESET_BUSY';
const AUTH_PASSWORD_RESET_SUCCESS = 'AUTH_PASSWORD_RESET_SUCCESS';
const AUTH_PASSWORD_RESET_FAILURE = 'AUTH_PASSWORD_RESET_FAILURE';

export {
  AUTH_SET_TOKEN,
  AUTH_LOGIN_BUSY,
  AUTH_LOGIN_SUCCESS,
  AUTH_LOGIN_FAILURE,
  AUTH_PASSWORD_RESET_BUSY,
  AUTH_PASSWORD_RESET_SUCCESS,
  AUTH_PASSWORD_RESET_FAILURE,
};
